### ISSUE TITLE
Where is SpotifyApi.NetCore.Samples ?

### ISSUE THREAD

**Issue by sugarshock** [Ringobot/SpotifyApi.NetCore#22]
Hey, I would love to use this wrapper  - unfortunetly I cant find the "seperate Samples repo" you're talking about on the readme. Is it down?

**Comment by DanielLarsenNZ** [comment]
Apologies @sugarshock, I had not pushed the samples repo since I split it out from this one. I have pushed it now but it has several issues including out of date frameworks and no documentation. I work on resolving these issues over the weekend.

The sample project is an ASP.NET Core API with a Vuejs SPA. 

There is also basic and advanced usage examples in the readme for this repo, as well as examples of usage in the Tests folder in this repo. 

Is there anything specific you are after? I am happy to provide sample code.

**Comment by DanielLarsenNZ** [comment]
Link to the Samples repo: https://github.com/Ringobot/SpotifyApi.NetCore.Samples

I will track the sample issues in that repo. Closing this issue for now.
